### ISSUE TITLE
org

### ISSUE THREAD

**Issue by dominictarr** [varstruct/varstruct#17]
@dcousens I would like to add you as collaborator.

Also, I think the time has come to move this to an org,
the essential thing about an org is that I can add others as "owners" and the owners are then able to add more collaborators, if it's under a user name, that user is the bottleneck for adding collaborators.

It took me a long while to realize that adding others was essential (because it turned out to be someone other than me which got the most use from the module) but they can't pass that on if they do not have the ability to add collaborators

**Comment by dcousens** [comment]
It may be not be perfectly suitable,  but [`bitcoinjs`](https://github.com/bitcoinjs) would be happy to foster it... especially given our continued usage of it (now,  and in future,  a lot).

**Comment by dcousens** [comment]
Otherwise maybe `cryptocoinjs`?  @jprichardson

**Comment by dcousens** [comment]
Its not really crypto related in any way though... but,  alas.

**Comment by dcousens** [comment]
ping @fanatid thoughts

**Comment by fanatid** [comment]
+1 for org, but not sure that bitcoinjs/cryptocoinjs/crypto-browserify is the best choices
do we have a lot https://github.com/mafintosh/abstract-encoding compliant modules? maybe special org?
ping @mafintosh

**Comment by dominictarr** [comment]
I was thinking a varstruct, or a var* org - also possibly @chrisdickenson would also like to transfer https://github.com/chrisdickinson/varint in? afterall, varint was the inspiration for varstruct's api.

Although, looking at the contributor lists on all of those modules, I do see mostly people who are interested in p2p or cryptocurrency

I'm certainly keen to move my modules from the list in abstract-encoding into the org.
other authors on that list, not already mentioned: @watson @jhiesey @themasch

**Comment by dcousens** [comment]
ping @chrisdickinson

**Comment by dcousens** [comment]
Did we still want to go ahead with this?

**Comment by dominictarr** [comment]
sure if you wanna

**Comment by fanatid** [comment]
@dominictarr please create org `varstruct` and move there this repo

**Comment by dominictarr** [comment]
done, and invited @fanatid and @dcousens to be owners

**Comment by dcousens** [comment]
Closing :+1:

**Comment by fanatid** [comment]
Thank you Dominic! Can you also move `varstruct-match`?
@dcousens I added you to owners on npm

**Comment by fanatid** [comment]
![1](https://cloud.githubusercontent.com/assets/2633065/23377980/3ca09dae-fd4b-11e6-91a5-a91a4b9bb79c.png)

**Comment by dominictarr** [comment]
moved.
