### ISSUE TITLE
Empty type

### ISSUE THREAD

**Issue by dcousens** [varstruct/varstruct#18]
### Usage
``` js
console.log(vstruct.Empty.encode())
// => Buffer < >

console.log(vstruct.Empty.decode(Buffer.alloc(0)))
// => Buffer < >

console.log(vstruct.Empty.decode(Buffer.alloc(1000)))
// => Buffer < >
```

No parameters,  returns empty buffer.

### Why?
Several layers deep in an abstraction,  and this solves the problem more elegantly than handling a `null` type all the way down... I suppose?

Thoughts?

**Comment by dominictarr** [comment]
can you give a plausible example where you would use this?

**Comment by dcousens** [comment]
I'm currently using my own wrapper around `levelup` for encoding,  e.g:

``` js
let aType = {
  key: vstruct([
    ['a', vstruct.UInt32LE],
    ['b', vstruct.UInt32LE]
  ],
  value: vstruct.Empty
}

ldb.put(aType, { a: 3, b: 15 })
```

This API is meant to be ambiguous enough that it can allow for such an empty type,  without having to handle a `null` type on its own.
It would certainly be possible for me to handle the `null` type,  but,  sometimes it is easier staying within the makeshift type system that we have created, than adding edge cases.

**Comment by dcousens** [comment]
You can probably a use case for https://github.com/dominictarr/varstruct/pull/16 too.

``` js
let aType = {
  key: vstruct([
    ['prefix', vstruct.Value('foo')],
    ['a', vstruct.UInt32LE],
    ['b', vstruct.UInt32LE]
  ],
  value: vstruct.Empty
}

ldb.put(aType, { a: 3, b: 15 }, undefined, cb)
```

**Comment by dominictarr** [comment]
got it. yeah I have needed to do this with leveldb too.

**Comment by fanatid** [comment]
`vstruct.Empty.encode(vstruct.Empty.decode(X)) === X` should be true, right?
In this case `vstruct.Empty.decode(Buffer.alloc(1000))` is not valid?

**Comment by dcousens** [comment]
```
vstruct.Empty.encode(vstruct.Empty.decode(X)) === X
```

No,  that would not work,  nor is an assumption this library maintains.

``` js
let b = Buffer.alloc(10)
// <Buffer 00 00 00 00 00 00 00 00 00 00>

varstruct.UInt32LE.encode(varstruct.UInt32LE.decode(b))
// <Buffer 00 00 00 00>
```

**Comment by dcousens** [comment]
Shall I make the PR?

**Comment by dominictarr** [comment]
when you do not pass a buffer in it creates on to encode into. The invaliant which should work is
``` js
deepEqual(value, decode(encode(value))
```

**Comment by dcousens** [comment]
``` js
varstruct.Empty.decode(varstruct.Empty.encode())
// <Buffer >
```

Would a `value` even be needed?

**Comment by dominictarr** [comment]
`''`?

**Comment by dominictarr** [comment]
or `null` or `undefined`

**Comment by dcousens** [comment]
@dominictarr so `undefined` would be fine?
I'll make a PR and see how it goes.

**Comment by dcousens** [comment]
I'm going to close this... it didn't really work out for me,  `null`/falsy ended up being a clearer alternative.
