### ISSUE TITLE
Numbers ignore parameter types

### ISSUE THREAD

**Issue by dcousens** [varstruct/varstruct#19]
``` js
varstruct.DoubleLE.encode('oh no a string')
// <Buffer 00 00 00 00 00 00 f8 7f>

varstruct.UInt32BE.encode(function () {})
// <Buffer 00 00 00 00>
```

I guess I shouldn't have expected otherwise... but maybe worth noting?

I think overall the potential for confusion is high here because there is an expectation of safety due to the explicit typing specified for the codec.

For reference,  [what my solution was](https://github.com/dcousens/indexd/commit/1fdd91b400d199c4ccf7b7d91660b7946dd966ba).

**Comment by fanatid** [comment]
Looks like I forgot to add type checking to Number :(
Do we really need all this type checks? It is very hard to keep them in actual condition.

**Comment by dcousens** [comment]
@fanatid `writeUInt32BE` doesn't throw on the above... so maybe we don't either.
It was just something I noticed after it caught me out.

**Comment by dcousens** [comment]
Closed in favour of https://github.com/varstruct/varstruct/pull/20
