### ISSUE TITLE
Type error consistency

### ISSUE THREAD

**Issue by dcousens** [varstruct/varstruct#22]
As found in https://github.com/varstruct/varstruct/pull/20,  our type related error messages now:

``` js
'value must be an Array instance'
'expected value as object, got ' + value
'value must be a Buffer instance'
'value must be a string'
```

Why did we do `+ value` in https://github.com/varstruct/varstruct/blob/master/lib/object.js#L23 ?

Do we want to make it consistent?

**Comment by fanatid** [comment]
Good catch. Never thought about this.
Are you ok with: `value must be X insance` ?
Unfortunately message changes lead us to major version bump :(

**Comment by dcousens** [comment]
I think `Expected <TYPE>, got <VALUE_TYPE> <VALUE>` is the format I went with in `typeforce`.

But,  that can be very difficult to handle sanely,  so `Expected <TYPE>` would be fine IMHO.

**Comment by dcousens** [comment]
Closing in favour of #32
