### ISSUE TITLE
Fixed multiple Array

### ISSUE THREAD

**Issue by dcousens** [varstruct/varstruct#23]
Often there are times where you have a fixed size structure,  but multiples of it.

Say you wanted to encode 100, 10 byte structures.
You could just send 1000 bytes, and the underlying transport protocol captures the length without needing to also provide it with the application layer;  which would just be able to see 1000 bytes / 10 is 100 structures.

Thoughts on this?
Worth adding?

**Comment by dominictarr** [comment]
You could do this, but would the difference really be worth it?

On the other hand, if you had a bit to indicate "more coming" (without giving the length) that would be cool, and you can then do streams where you don't actually know the length yet! (this is how varints work, too)

**Comment by dcousens** [comment]
Maybe some other time,  it was mostly useful for interacting with *existing* protocols,  tbh.
