### ISSUE TITLE
Decoding a non-Buffer

### ISSUE THREAD

**Issue by dcousens** [varstruct/varstruct#24]
Thoughts on whether this is a bug?

``` js
v.UInt8.decode('h')
> 'h'
```

**Comment by dcousens** [comment]
IMHO,  we should probably throw `new TypeError('buffer must be a Buffer instance')`

**Comment by dominictarr** [comment]
👍 must be `Buffer.isBuffer(v)`

**Comment by dcousens** [comment]
Fixed in https://github.com/varstruct/varstruct/commit/beb4c4bf12e911075139cb6abebf08605fede265
